const router = require('koa-router')()
const warehouse = require('./warehouse')
const reservoir = require('./reservoir')
const logistics = require('./logistics')
const storage = require('./storage')
const user = require('./user')
const vehicle = require('./vehicle')
const delivery = require('./delivery')
const auth = require('./auth')
const dashboard = require('./dashboard')
const log = require('./log')

router.use('/api', warehouse.routes(), warehouse.allowedMethods())
router.use('/api', reservoir.routes(), reservoir.allowedMethods())
router.use('/api', logistics.routes(), logistics.allowedMethods())
router.use('/api', storage.routes(), storage.allowedMethods())
router.use('/api', user.routes(), user.allowedMethods())
router.use('/api', vehicle.routes(), vehicle.allowedMethods())
router.use('/api', delivery.routes(), delivery.allowedMethods())
router.use('/api', auth.routes(), auth.allowedMethods())
router.use('/api', dashboard.routes(), dashboard.allowedMethods())
router.use('/api', log.routes(), log.allowedMethods())

module.exports = router
